import type { Metadata } from "next";
import "./index.css";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			className="h-full antialiased"
		>
			<body className="min-h-full flex flex-col">
				<nav className="sticky flex bg-main text-white  w-full text-lg p-1 justify-between">
					<div className="flex gap-1">
						<a href="/">Home</a>
						<a href="/users">Users</a>
					</div>
				</nav>
				<main className="p-1.5">{children}</main>
			</body>
		</html>
	);
}
